/* ============================================================
   cairn — client-side engine
   Renders the site from manifest.json (auto-generated by
   scripts/build-manifest.mjs — never hand-edited).
   All content files are treated as UNTRUSTED:
   - Markdown -> marked -> DOMPurify.sanitize before display.
   - Quiz/manifest strings -> HTML-escaped before display.
   No study content lives in this file. See CLAUDE.md.
   ============================================================ */
(function () {
  "use strict";

  var CFG = window.SITE_CONFIG || {};
  var V = encodeURIComponent(window.ASSET_V || "1");

  /* ---------------- site chrome translations ---------------- */
  var STRINGS = {
    en: {
      navSubjects: "Subjects", navQuizzes: "Quizzes", navPapers: "Papers",
      subjects: "Subjects", notes: "Notes", quizzes: "Quizzes", papers: "Exam papers",
      note: "Note", quiz: "Quiz", paper: "Paper", home: "Home", back: "Back",
      loading: "Loading", emptyTag: "Status — empty",
      searchPlaceholder: "Search notes, quizzes, papers…", searchAction: "Search",
      latestNotes: "Latest notes", allSubjects: "All subjects",
      emptyNotesTitle: "No notes yet",
      emptyNotesHint: "Notes appear here automatically the moment a note file is dropped into the content/lectures folder on GitHub.",
      emptyQuizzesTitle: "No quizzes yet",
      emptyQuizzesHint: "Quizzes appear here automatically once a quiz file is dropped into the content/quizzes folder on GitHub.",
      emptyPapersTitle: "No exam papers yet",
      emptyPapersHint: "Exam papers appear here automatically once a paper file is dropped into the content/exam-papers folder on GitHub.",
      emptySubject: "Nothing here yet",
      notFoundTitle: "Page not found",
      notFoundHint: "This link points to something that does not exist (yet).",
      loadErrorTitle: "Could not load this file",
      loadErrorHint: "The file may have been renamed or removed. Go back and try again.",
      indexErrorTitle: "Site index not ready",
      indexErrorHint: "manifest.json is generated automatically when the site is published on GitHub. Running locally? Run: node scripts/build-manifest.mjs",
      answered: "Answered", correct: "Correct", explanation: "Why",
      yourScore: "Your score", retry: "Try again",
      takeQuiz: "Take the quiz", relatedNote: "Read the note",
      startQuiz: "Start quiz", openPaper: "Open paper", readNote: "Read note",
      showKey: "Show answer key", hideKey: "Hide answer key",
      print: "Print", answerKey: "Answer key",
      resultsFor: "Results for", noResultsTitle: "Nothing found",
      noResultsHint: "Try a shorter word, or check the spelling.",
      settings: "Settings", language: "Language", textSize: "Text size",
      sizeS: "Small", sizeM: "Medium", sizeL: "Large", close: "Close",
      theme: "Appearance", themeLight: "Light", themeDark: "Dark", themeAuto: "Auto",
      disclaimerLabel: "Disclaimer", questionsWord: "questions",
      moreSoon: "More options will live here as the site grows."
    },
    ms: {
      navSubjects: "Subjek", navQuizzes: "Kuiz", navPapers: "Kertas",
      subjects: "Subjek", notes: "Nota", quizzes: "Kuiz", papers: "Kertas peperiksaan",
      note: "Nota", quiz: "Kuiz", paper: "Kertas", home: "Utama", back: "Kembali",
      loading: "Memuatkan", emptyTag: "Status — kosong",
      searchPlaceholder: "Cari nota, kuiz, kertas…", searchAction: "Cari",
      latestNotes: "Nota terkini", allSubjects: "Semua subjek",
      emptyNotesTitle: "Belum ada nota",
      emptyNotesHint: "Nota akan muncul di sini secara automatik sebaik sahaja fail nota diletakkan dalam folder content/lectures di GitHub.",
      emptyQuizzesTitle: "Belum ada kuiz",
      emptyQuizzesHint: "Kuiz akan muncul di sini secara automatik sebaik sahaja fail kuiz diletakkan dalam folder content/quizzes di GitHub.",
      emptyPapersTitle: "Belum ada kertas peperiksaan",
      emptyPapersHint: "Kertas peperiksaan akan muncul di sini secara automatik sebaik sahaja fail diletakkan dalam folder content/exam-papers di GitHub.",
      emptySubject: "Belum ada apa-apa di sini",
      notFoundTitle: "Halaman tidak dijumpai",
      notFoundHint: "Pautan ini menuju ke sesuatu yang belum wujud.",
      loadErrorTitle: "Fail tidak dapat dimuatkan",
      loadErrorHint: "Fail mungkin telah dinamakan semula atau dipadam. Sila kembali dan cuba lagi.",
      indexErrorTitle: "Indeks laman belum sedia",
      indexErrorHint: "manifest.json dijana secara automatik semasa laman diterbitkan di GitHub. Jalankan secara lokal: node scripts/build-manifest.mjs",
      answered: "Dijawab", correct: "Betul", explanation: "Kenapa",
      yourScore: "Markah anda", retry: "Cuba lagi",
      takeQuiz: "Jawab kuiz", relatedNote: "Baca nota",
      startQuiz: "Mula kuiz", openPaper: "Buka kertas", readNote: "Baca nota",
      showKey: "Tunjuk skema jawapan", hideKey: "Sembunyikan skema jawapan",
      print: "Cetak", answerKey: "Skema jawapan",
      resultsFor: "Hasil carian untuk", noResultsTitle: "Tiada hasil",
      noResultsHint: "Cuba perkataan lebih pendek, atau semak ejaan.",
      settings: "Tetapan", language: "Bahasa", textSize: "Saiz teks",
      sizeS: "Kecil", sizeM: "Sedang", sizeL: "Besar", close: "Tutup",
      theme: "Penampilan", themeLight: "Cerah", themeDark: "Gelap", themeAuto: "Auto",
      disclaimerLabel: "Penafian", questionsWord: "soalan",
      moreSoon: "Lebih banyak pilihan akan ditambah di sini."
    }
  };

  /* ---------------- preferences (Settings sheet) ---------------- */
  var PREF_LANG = "nova.lang";
  var PREF_SIZE = "nova.textsize";
  var PREF_THEME = "nova.theme";
  function getPref(key, fallback) {
    try { return localStorage.getItem(key) || fallback; } catch (err) { return fallback; }
  }
  function setPref(key, value) {
    try { localStorage.setItem(key, value); } catch (err) { /* private mode: ignore */ }
  }
  function lang() {
    var l = getPref(PREF_LANG, CFG.defaultLang || "en");
    return STRINGS[l] ? l : "en";
  }
  function textSize() {
    var s = getPref(PREF_SIZE, "m");
    return ["s", "m", "l"].indexOf(s) >= 0 ? s : "m";
  }
  function theme() {
    var v = getPref(PREF_THEME, "auto");
    return ["light", "dark", "auto"].indexOf(v) >= 0 ? v : "auto";
  }
  function t(key) {
    var table = STRINGS[lang()];
    return (table && table[key]) || STRINGS.en[key] || key;
  }
  function pick(value) {
    if (!value) return "";
    if (typeof value === "string" || Array.isArray(value)) return value;
    return value[lang()] || value.en || "";
  }

  /* ---------------- tiny helpers ---------------- */
  function esc(value) {
    return String(value == null ? "" : value)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }
  function pad2(n) {
    n = Number(n) || 0;
    return (n < 10 ? "0" : "") + n;
  }
  function dirOf(path) {
    return path.slice(0, path.lastIndexOf("/"));
  }

  var ICONS = {
    arrow: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 8h13M9 3l5 5-5 5"/></svg>',
    search: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="7" cy="7" r="5"/><path d="M11 11l4 4"/></svg>',
    sliders: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 4h8M13 4h2M1 12h2M7 12h8"/><circle cx="11" cy="4" r="1.8"/><circle cx="4.5" cy="12" r="1.8"/></svg>',
    close: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M3 3l10 10M13 3L3 13"/></svg>',
    check: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M2.5 8.5l3.5 3.5L13.5 4"/></svg>',
    cross: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 3l10 10M13 3L3 13"/></svg>',
    print: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M4 6V2h8v4M4 11H2V6h12v5h-2M4 9h8v5H4z"/></svg>'
  };

  /* ---------------- manifest state ---------------- */
  var manifest = { subjects: [], notes: [], quizzes: [], papers: [] };
  var manifestFailed = false;
  var renderToken = 0;
  var appEl = null;
  var layerEl = null;

  function normalizeManifest(data) {
    data = data || {};
    return {
      subjects: Array.isArray(data.subjects) ? data.subjects : [],
      notes: Array.isArray(data.notes) ? data.notes : [],
      quizzes: Array.isArray(data.quizzes) ? data.quizzes : [],
      papers: Array.isArray(data.papers) ? data.papers : []
    };
  }
  function loadManifest() {
    return fetch("manifest.json?v=" + V, { cache: "no-cache" })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .then(function (data) { manifest = normalizeManifest(data); })
      .catch(function (err) {
        console.error("[cairn] manifest load failed:", err);
        manifest = normalizeManifest(null);
        manifestFailed = true;
      });
  }
  function fetchText(path) {
    return fetch(encodeURI(path) + "?v=" + V, { cache: "no-cache" }).then(function (res) {
      if (!res.ok) throw new Error("HTTP " + res.status);
      return res.text();
    });
  }

  /* ---------------- manifest queries ---------------- */
  function subjectList() {
    var configured = Array.isArray(CFG.subjects) ? CFG.subjects.slice() : [];
    var discovered = manifest.subjects.filter(function (s) {
      return configured.indexOf(s) === -1;
    }).sort();
    return configured.concat(discovered);
  }
  function byDateDesc(a, b) {
    return String(b.sort || "").localeCompare(String(a.sort || "")) ||
           String(a.topic || a.title || "").localeCompare(String(b.topic || b.title || ""));
  }
  function notesFor(subject) {
    return manifest.notes.filter(function (n) { return n.subject === subject; }).sort(byDateDesc);
  }
  function quizzesFor(subject) {
    return manifest.quizzes.filter(function (q) { return q.subject === subject; });
  }
  function papersFor(subject) {
    return manifest.papers.filter(function (p) { return p.subject === subject; });
  }
  function findNote(subject, file) {
    return manifest.notes.filter(function (n) { return n.subject === subject && n.file === file; })[0];
  }
  function findQuiz(subject, id) {
    return manifest.quizzes.filter(function (q) { return q.subject === subject && q.id === id; })[0];
  }
  function findPaper(subject, file) {
    return manifest.papers.filter(function (p) { return p.subject === subject && p.file === file; })[0];
  }

  /* ---------------- markdown (untrusted -> sanitized) ---------------- */
  function stripFrontmatter(src) {
    var match = /^﻿?\s*---[^\n]*\n[\s\S]*?\n---[^\n]*\n?/.exec(src);
    return match ? src.slice(match[0].length) : src;
  }
  function fixRelativeMedia(html, baseDir) {
    var tpl = document.createElement("template");
    tpl.innerHTML = html;
    var images = tpl.content.querySelectorAll("img[src]");
    for (var i = 0; i < images.length; i++) {
      var src = images[i].getAttribute("src") || "";
      if (!/^(https?:|data:|\/|#)/i.test(src)) {
        images[i].setAttribute("src", baseDir + "/" + src);
      }
    }
    return tpl.innerHTML;
  }
  function renderMarkdown(src, baseDir) {
    if (!window.marked || !window.DOMPurify) {
      console.error("[cairn] marked/DOMPurify not loaded");
      return "<p>" + esc(t("loadErrorHint")) + "</p>";
    }
    var raw = window.marked.parse(src, { gfm: true, breaks: true, async: false });
    var clean = window.DOMPurify.sanitize(raw, { USE_PROFILES: { html: true } });
    return fixRelativeMedia(clean, baseDir);
  }

  /* ---------------- routing ---------------- */
  function route() {
    var hash = location.hash.replace(/^#\/?/, "");
    if (!hash) return { name: "home", parts: [] };
    var parts = hash.split("/").map(function (part) {
      try { return decodeURIComponent(part); } catch (err) { return part; }
    });
    return { name: parts[0] || "home", parts: parts.slice(1) };
  }
  function href() {
    var parts = Array.prototype.slice.call(arguments);
    return "#/" + parts.map(encodeURIComponent).join("/");
  }

  /* ---------------- chrome (header / footer / shells) ---------------- */
  function headerHtml(active) {
    function cls(name) { return active === name ? ' class="is-active"' : ""; }
    return '<header class="site-head">' +
      '<div class="wrap">' +
        '<a class="brand" href="#/">' + esc(CFG.siteName || "cairn") + "</a>" +
        '<nav class="site-nav" aria-label="Main">' +
          '<a href="' + href("subjects") + '"' + cls("subjects") + ">" + esc(t("navSubjects")) + "</a>" +
          '<a href="' + href("quizzes") + '"' + cls("quizzes") + ">" + esc(t("navQuizzes")) + "</a>" +
          '<a href="' + href("papers") + '"' + cls("papers") + ">" + esc(t("navPapers")) + "</a>" +
        "</nav>" +
        '<button type="button" class="icon-btn" data-action="open-settings" aria-label="' + esc(t("settings")) + '">' +
          ICONS.sliders +
        "</button>" +
      "</div></header>";
  }
  function footerHtml() {
    return '<footer class="site-foot">' +
      '<div class="wrap">' +
        '<div class="foot-brand">' + esc(CFG.siteName || "cairn") + '<span class="dot">.</span></div>' +
        '<p class="foot-disclaimer"><span class="mono-label">' + esc(t("disclaimerLabel")) + " — </span>" +
          esc(pick(CFG.disclaimer)) + "</p>" +
        '<div class="foot-meta">' +
          '<span class="mono-label">' + esc(CFG.siteName || "cairn") + " · static archive · github pages</span>" +
          '<button type="button" class="mono-label" data-action="open-settings">' + esc(t("settings")) + "</button>" +
        "</div>" +
      "</div></footer>";
  }
  function paint(active, mainHtml) {
    appEl.innerHTML = headerHtml(active) + '<main id="view">' + mainHtml + "</main>" + footerHtml();
    window.scrollTo(0, 0);
  }
  function paintView(html) {
    var view = document.getElementById("view");
    if (view) view.innerHTML = html;
  }
  function sectionPaper(inner) {
    return '<section class="sec sec--paper"><div class="wrap">' + inner + "</div></section>";
  }
  function crumbsHtml(items) {
    var parts = items.map(function (item) {
      return item.href
        ? '<a href="' + item.href + '">' + esc(item.label) + "</a>"
        : "<span>" + esc(item.label) + "</span>";
    });
    return '<nav class="crumbs" aria-label="Breadcrumb">' + parts.join('<span class="sep">/</span>') + "</nav>";
  }
  function labelRow(left, right) {
    return '<div class="label-row"><span class="mono-label">' + left + "</span>" +
      (right != null ? '<span class="mono-label">' + right + "</span>" : "") + "</div>";
  }
  function emptyBox(titleKey, hintKey) {
    return '<div class="empty">' +
      '<span class="mono-label">' + esc(t("emptyTag")) + "</span>" +
      '<div class="empty-title">' + esc(t(titleKey)) + "</div>" +
      '<p class="empty-hint">' + esc(t(hintKey)) + "</p>" +
    "</div>";
  }
  function loadingHtml() {
    return sectionPaper('<span class="mono-label">' + esc(t("loading")) + " …</span>");
  }
  function notFoundHtml() {
    return sectionPaper(
      crumbsHtml([{ label: t("home"), href: "#/" }]) +
      '<div class="empty">' +
        '<span class="mono-label">404</span>' +
        '<div class="empty-title">' + esc(t("notFoundTitle")) + "</div>" +
        '<p class="empty-hint">' + esc(t("notFoundHint")) + "</p>" +
        '<a class="pill pill--acid" href="#/">' + esc(t("home")) + "</a>" +
      "</div>"
    );
  }
  function loadErrorHtml(backHref) {
    return sectionPaper(
      '<div class="empty">' +
        '<span class="mono-label">' + esc(t("emptyTag")) + "</span>" +
        '<div class="empty-title">' + esc(t("loadErrorTitle")) + "</div>" +
        '<p class="empty-hint">' + esc(t("loadErrorHint")) + "</p>" +
        '<a class="pill pill--acid" href="' + backHref + '">' + esc(t("back")) + "</a>" +
      "</div>"
    );
  }

  /* ---------------- shared list pieces ---------------- */
  function noteRow(note, index) {
    return '<a class="row" href="' + href("note", note.subject, note.file) + '">' +
      '<span class="row-num">' + pad2(index + 1) + "</span>" +
      '<span class="row-main">' +
        '<span class="mono-label row-meta">' + esc(note.subject) +
          (note.date ? " · " + esc(note.date) : "") + " · " + esc(t("note")) + "</span>" +
        '<span class="row-title">' + esc(note.topic) + "</span>" +
        (note.summary ? '<span class="row-sub">' + esc(note.summary) + "</span>" : "") +
      "</span>" +
      '<span class="row-end"><span class="row-arrow">' + ICONS.arrow + "</span></span>" +
    "</a>";
  }
  function quizRow(quizMeta, index) {
    return '<a class="row" href="' + href("quiz", quizMeta.subject, quizMeta.id) + '">' +
      '<span class="row-num">' + pad2(index + 1) + "</span>" +
      '<span class="row-main">' +
        '<span class="mono-label row-meta">' + esc(quizMeta.subject) + " · " + esc(t("quiz")) +
          " · " + pad2(quizMeta.count) + " " + esc(t("questionsWord")) + "</span>" +
        '<span class="row-title">' + esc(quizMeta.title) + "</span>" +
      "</span>" +
      '<span class="row-end"><span class="row-arrow">' + ICONS.arrow + "</span></span>" +
    "</a>";
  }
  function paperRow(paper, index) {
    return '<a class="row" href="' + href("paper", paper.subject, paper.file) + '">' +
      '<span class="row-num">' + pad2(index + 1) + "</span>" +
      '<span class="row-main">' +
        '<span class="mono-label row-meta">' + esc(paper.subject) + " · " + esc(t("paper")) + "</span>" +
        '<span class="row-title">' + esc(paper.title) + "</span>" +
      "</span>" +
      '<span class="row-end"><span class="row-arrow">' + ICONS.arrow + "</span></span>" +
    "</a>";
  }
  function searchFormHtml(prefill) {
    return '<form class="search-form" data-search role="search">' +
      '<input class="search-input" type="search" name="q" value="' + esc(prefill || "") + '"' +
        ' placeholder="' + esc(t("searchPlaceholder")) + '" aria-label="' + esc(t("searchAction")) + '">' +
      '<button class="search-btn" type="submit" aria-label="' + esc(t("searchAction")) + '">' + ICONS.search + "</button>" +
    "</form>";
  }

  /* ---------------- views ---------------- */
  function homeHtml() {
    var subjects = subjectList();
    var latest = manifest.notes.slice().sort(byDateDesc).slice(0, 6);
    var lines = pick(CFG.heroLines);
    if (!Array.isArray(lines)) lines = [];
    var year = new Date().getFullYear();

    var hero = '<section class="sec--ink hero-sec">' +
      '<div class="wrap">' +
        '<div class="hero-kicker">' +
          '<span class="mono-label">' + esc(pick(CFG.heroKicker)) + "</span>" +
          '<span class="mono-label">Vol. 02 — ' + year + "</span>" +
        "</div>" +
        '<h1 class="wordmark">' + esc(CFG.siteName || "cairn") + '<span class="dot">.</span></h1>' +
        '<div class="statement">' +
          lines.map(function (line) {
            return '<span class="statement-line">' + esc(line) + "</span>";
          }).join("") +
        "</div>" +
        '<div class="hero-foot">' +
          '<div class="stat"><span class="stat-num">' + pad2(manifest.notes.length) + '</span><span class="mono-label">' + esc(t("notes")) + "</span></div>" +
          '<div class="stat"><span class="stat-num">' + pad2(manifest.quizzes.length) + '</span><span class="mono-label">' + esc(t("quizzes")) + "</span></div>" +
          '<div class="stat"><span class="stat-num">' + pad2(manifest.papers.length) + '</span><span class="mono-label">' + esc(t("papers")) + "</span></div>" +
        "</div>" +
      "</div></section>";

    var banner = '<section class="sec--acid banner"><div class="wrap">' +
      '<span class="mono-label">' + esc(t("disclaimerLabel")) + "</span>" +
      '<p class="banner-text">' + esc(pick(CFG.disclaimer)) + "</p>" +
    "</div></section>";

    var search = '<section class="sec sec--paper sec--tight"><div class="wrap">' +
      searchFormHtml("") +
    "</div></section>";

    var indexWarning = manifestFailed
      ? '<section class="sec sec--paper sec--tight"><div class="wrap">' + emptyBox("indexErrorTitle", "indexErrorHint") + "</div></section>"
      : "";

    var latestSection = '<section class="sec sec--paper"><div class="wrap">' +
      labelRow(esc(t("latestNotes")), pad2(latest.length)) +
      (latest.length
        ? '<div class="card-grid">' + latest.map(function (note) {
            return '<a class="card" href="' + href("note", note.subject, note.file) + '">' +
              '<span class="mono-label">' + esc(note.subject) + (note.date ? " · " + esc(note.date) : "") + "</span>" +
              '<span class="card-title">' + esc(note.topic) + "</span>" +
              (note.summary ? '<span class="card-sub">' + esc(note.summary) + "</span>" : "") +
              '<span class="card-foot"><span class="mono-label">' + esc(t("readNote")) + "</span>" + ICONS.arrow + "</span>" +
            "</a>";
          }).join("") + "</div>"
        : emptyBox("emptyNotesTitle", "emptyNotesHint")) +
    "</div></section>";

    var subjectsSection = '<section class="sec sec--paper" style="padding-top:0"><div class="wrap">' +
      labelRow(esc(t("allSubjects")), pad2(subjects.length)) +
      subjectRowsHtml(subjects) +
    "</div></section>";

    return hero + banner + search + indexWarning + latestSection + subjectsSection;
  }

  function subjectRowsHtml(subjects) {
    return '<div class="index-rows">' + subjects.map(function (subject, i) {
      var n = notesFor(subject).length;
      var q = quizzesFor(subject).length;
      var p = papersFor(subject).length;
      var counts = (n + q + p) === 0
        ? esc(t("emptySubject"))
        : esc([
            n + " " + t("notes").toLowerCase(),
            q + " " + t("quizzes").toLowerCase(),
            p + " " + t("papers").toLowerCase()
          ].join(" · "));
      return '<a class="row" href="' + href("subject", subject) + '">' +
        '<span class="row-num">' + pad2(i + 1) + "</span>" +
        '<span class="row-main">' +
          '<span class="row-title">' + esc(subject) + "</span>" +
          '<span class="row-sub">' + counts + "</span>" +
        "</span>" +
        '<span class="row-end"><span class="row-arrow">' + ICONS.arrow + "</span></span>" +
      "</a>";
    }).join("") + "</div>";
  }

  function subjectsPageHtml() {
    return sectionPaper(
      crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("subjects") }]) +
      '<div class="page-head"><h1 class="page-title page-title--sans">' + esc(t("subjects")) + "</h1></div>" +
      subjectRowsHtml(subjectList())
    );
  }

  function subjectPageHtml(subject) {
    var known = subjectList().indexOf(subject) !== -1;
    if (!known) return notFoundHtml();
    var notes = notesFor(subject);
    var quizzes = quizzesFor(subject);
    var papers = papersFor(subject);
    var body =
      crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("subjects"), href: href("subjects") }, { label: subject }]) +
      '<div class="page-head">' +
        '<h1 class="page-title page-title--sans">' + esc(subject) + "</h1>" +
      "</div>" +
      '<div class="stack">' +
        labelRow(esc(t("notes")), pad2(notes.length)) +
        (notes.length
          ? '<div class="index-rows">' + notes.map(noteRow).join("") + "</div>"
          : emptyBox("emptyNotesTitle", "emptyNotesHint")) +
        labelRow(esc(t("quizzes")), pad2(quizzes.length)) +
        (quizzes.length
          ? '<div class="index-rows">' + quizzes.map(quizRow).join("") + "</div>"
          : emptyBox("emptyQuizzesTitle", "emptyQuizzesHint")) +
        labelRow(esc(t("papers")), pad2(papers.length)) +
        (papers.length
          ? '<div class="index-rows">' + papers.map(paperRow).join("") + "</div>"
          : emptyBox("emptyPapersTitle", "emptyPapersHint")) +
      "</div>";
    return sectionPaper(body);
  }

  function quizzesPageHtml() {
    var all = manifest.quizzes;
    var body = crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("quizzes") }]) +
      '<div class="page-head"><h1 class="page-title page-title--sans">' + esc(t("quizzes")) + "</h1></div>";
    if (!all.length) return sectionPaper(body + emptyBox("emptyQuizzesTitle", "emptyQuizzesHint"));
    var grouped = subjectList().map(function (subject) {
      var items = quizzesFor(subject);
      if (!items.length) return "";
      return labelRow(esc(subject), pad2(items.length)) +
        '<div class="index-rows">' + items.map(quizRow).join("") + "</div>";
    }).join("");
    return sectionPaper(body + '<div class="stack">' + grouped + "</div>");
  }

  function papersPageHtml() {
    var all = manifest.papers;
    var body = crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("papers") }]) +
      '<div class="page-head"><h1 class="page-title page-title--sans">' + esc(t("papers")) + "</h1></div>";
    if (!all.length) return sectionPaper(body + emptyBox("emptyPapersTitle", "emptyPapersHint"));
    var grouped = subjectList().map(function (subject) {
      var items = papersFor(subject);
      if (!items.length) return "";
      return labelRow(esc(subject), pad2(items.length)) +
        '<div class="index-rows">' + items.map(paperRow).join("") + "</div>";
    }).join("");
    return sectionPaper(body + '<div class="stack">' + grouped + "</div>");
  }

  function searchPageHtml(query) {
    var needle = String(query || "").trim().toLowerCase();
    function hit(value) { return String(value || "").toLowerCase().indexOf(needle) !== -1; }
    var noteHits = needle ? manifest.notes.filter(function (n) { return hit(n.subject) || hit(n.topic) || hit(n.summary); }) : [];
    var quizHits = needle ? manifest.quizzes.filter(function (q) { return hit(q.subject) || hit(q.title); }) : [];
    var paperHits = needle ? manifest.papers.filter(function (p) { return hit(p.subject) || hit(p.title); }) : [];
    var total = noteHits.length + quizHits.length + paperHits.length;

    var body = crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("searchAction") }]) +
      '<div class="page-head">' +
        '<span class="mono-label page-meta">' + esc(t("resultsFor")) + " “" + esc(query) + "” — " + pad2(total) + "</span>" +
        searchFormHtml(query) +
      "</div>";

    if (!total) {
      return sectionPaper(body +
        '<div class="empty">' +
          '<span class="mono-label">' + esc(t("emptyTag")) + "</span>" +
          '<div class="empty-title">' + esc(t("noResultsTitle")) + "</div>" +
          '<p class="empty-hint">' + esc(t("noResultsHint")) + "</p>" +
        "</div>");
    }
    var out = "";
    if (noteHits.length) out += labelRow(esc(t("notes")), pad2(noteHits.length)) + '<div class="index-rows">' + noteHits.map(noteRow).join("") + "</div>";
    if (quizHits.length) out += labelRow(esc(t("quizzes")), pad2(quizHits.length)) + '<div class="index-rows">' + quizHits.map(quizRow).join("") + "</div>";
    if (paperHits.length) out += labelRow(esc(t("papers")), pad2(paperHits.length)) + '<div class="index-rows">' + paperHits.map(paperRow).join("") + "</div>";
    return sectionPaper(body + '<div class="stack">' + out + "</div>");
  }

  /* ---------------- note view (async fetch) ---------------- */
  function notePage(subject, file) {
    var note = findNote(subject, file);
    if (!note) { paint("subjects", notFoundHtml()); return; }
    paint("subjects", loadingHtml());
    var token = renderToken;
    fetchText(note.path).then(function (md) {
      if (token !== renderToken) return;
      var html = renderMarkdown(stripFrontmatter(md), dirOf(note.path));
      var quizMeta = note.quiz ? findQuiz(subject, note.quiz) : null;
      paintView(sectionPaper(
        crumbsHtml([
          { label: t("home"), href: "#/" },
          { label: subject, href: href("subject", subject) },
          { label: t("note") }
        ]) +
        '<div class="page-head">' +
          '<span class="mono-label page-meta">' + esc(subject) +
            (note.date ? " · " + esc(note.date) : "") + " · " + esc(t("note")) + "</span>" +
          '<h1 class="page-title">' + esc(note.topic) + "</h1>" +
          (note.summary ? '<p class="page-sub">' + esc(note.summary) + "</p>" : "") +
          (quizMeta
            ? '<div class="page-actions"><a class="pill pill--acid" href="' + href("quiz", subject, quizMeta.id) + '">' +
                esc(t("takeQuiz")) + " " + ICONS.arrow + "</a></div>"
            : "") +
        "</div>" +
        '<article class="prose">' + html + "</article>" +
        '<div class="page-actions"><a class="pill pill--outline" href="' + href("subject", subject) + '">' + esc(t("back")) + "</a></div>"
      ));
    }).catch(function (err) {
      console.error("[cairn] note load failed:", err);
      if (token !== renderToken) return;
      paintView(loadErrorHtml(href("subject", subject)));
    });
  }

  /* ---------------- quiz view (async fetch + interaction) ---------------- */
  var quizState = null;

  function validQuestions(data) {
    var list = (data && Array.isArray(data.questions)) ? data.questions : [];
    return list.filter(function (q) {
      return q && typeof q.q === "string" && q.q.trim() &&
        Array.isArray(q.options) && q.options.length >= 2 &&
        typeof q.answer === "number" && q.answer >= 0 && q.answer < q.options.length;
    });
  }

  function quizPage(subject, id) {
    var meta = findQuiz(subject, id);
    if (!meta) { paint("quizzes", notFoundHtml()); return; }
    paint("quizzes", loadingHtml());
    var token = renderToken;
    fetchText(meta.path).then(function (text) {
      if (token !== renderToken) return;
      var data;
      try { data = JSON.parse(text); } catch (err) { throw new Error("bad JSON: " + err.message); }
      var questions = validQuestions(data);
      if (!questions.length) { paintView(loadErrorHtml(href("subject", subject))); return; }
      quizState = { total: questions.length, answered: 0, correct: 0 };
      var relatedNote = manifest.notes.filter(function (n) {
        return n.subject === subject && n.quiz === id;
      })[0];

      var blocks = questions.map(function (q, qi) {
        var opts = q.options.map(function (option, oi) {
          return '<button type="button" class="opt" data-action="quiz-option" data-opt="' + oi + '">' +
            '<span class="opt-key">' + String.fromCharCode(65 + oi) + "</span>" +
            "<span>" + esc(option) + "</span>" +
            '<span class="opt-mark-slot" aria-hidden="true"></span>' +
          "</button>";
        }).join("");
        var explain = (typeof q.explain === "string" && q.explain.trim())
          ? '<div class="explain"><span class="mono-label">' + esc(t("explanation")) + "</span>" + esc(q.explain) + "</div>"
          : "";
        return '<div class="q-block" data-answer="' + q.answer + '">' +
          '<div class="q-head"><span class="mono-label">Q' + pad2(qi + 1) + '</span><span class="q-text">' + esc(q.q) + "</span></div>" +
          '<div class="opts">' + opts + "</div>" + explain +
        "</div>";
      }).join("");

      paintView(sectionPaper(
        crumbsHtml([
          { label: t("home"), href: "#/" },
          { label: subject, href: href("subject", subject) },
          { label: t("quiz") }
        ]) +
        '<div class="page-head">' +
          '<span class="mono-label page-meta">' + esc(subject) + " · " + esc(t("quiz")) +
            " · " + pad2(questions.length) + " " + esc(t("questionsWord")) + "</span>" +
          '<h1 class="page-title">' + esc(data.title || meta.title) + "</h1>" +
          (relatedNote
            ? '<div class="page-actions"><a class="pill pill--outline" href="' + href("note", subject, relatedNote.file) + '">' + esc(t("relatedNote")) + "</a></div>"
            : "") +
        "</div>" +
        '<div class="quiz-bar">' +
          '<span class="mono-label">' + esc(t("answered")) + ' <strong id="quiz-answered">00</strong>/' + pad2(questions.length) + "</span>" +
          '<span class="mono-label">' + esc(t("correct")) + ' <strong id="quiz-correct">00</strong></span>' +
        "</div>" +
        blocks +
        '<div class="quiz-final" id="quiz-final">' +
          '<span class="mono-label">' + esc(t("yourScore")) + "</span>" +
          '<div class="score-big" id="quiz-score"></div>' +
          '<div class="page-actions">' +
            '<button type="button" class="pill pill--acid" data-action="retry-quiz">' + esc(t("retry")) + "</button>" +
            '<a class="pill pill--outline" href="' + href("subject", subject) + '">' + esc(t("back")) + "</a>" +
          "</div>" +
        "</div>"
      ));
    }).catch(function (err) {
      console.error("[cairn] quiz load failed:", err);
      if (token !== renderToken) return;
      paintView(loadErrorHtml(href("subject", subject)));
    });
  }

  function handleQuizOption(button) {
    var block = button.closest(".q-block");
    if (!block || block.getAttribute("data-done") === "1" || !quizState) return;
    block.setAttribute("data-done", "1");
    var answer = parseInt(block.getAttribute("data-answer"), 10);
    var picked = parseInt(button.getAttribute("data-opt"), 10);
    var options = block.querySelectorAll(".opt");
    for (var i = 0; i < options.length; i++) {
      options[i].disabled = true;
      var slot = options[i].querySelector(".opt-mark-slot");
      if (i === answer) {
        options[i].classList.add("is-correct");
        if (slot) slot.innerHTML = ICONS.check;
      } else if (i === picked) {
        options[i].classList.add("is-wrong");
        if (slot) slot.innerHTML = ICONS.cross;
      } else {
        options[i].classList.add("is-dim");
      }
    }
    var explain = block.querySelector(".explain");
    if (explain) explain.classList.add("is-open");

    quizState.answered += 1;
    if (picked === answer) quizState.correct += 1;
    var answeredEl = document.getElementById("quiz-answered");
    var correctEl = document.getElementById("quiz-correct");
    if (answeredEl) answeredEl.textContent = pad2(quizState.answered);
    if (correctEl) correctEl.textContent = pad2(quizState.correct);

    if (quizState.answered === quizState.total) {
      var finalPanel = document.getElementById("quiz-final");
      var score = document.getElementById("quiz-score");
      if (score) score.textContent = quizState.correct + "/" + quizState.total;
      if (finalPanel) {
        finalPanel.classList.add("is-open");
        finalPanel.scrollIntoView({ behavior: "smooth", block: "center" });
      }
    }
  }

  /* ---------------- exam paper view (async fetch) ---------------- */
  function splitAnswerKey(md) {
    var match = /^##\s+(answer key|skema jawapan)\s*$/im.exec(md);
    if (!match) return { body: md, key: "" };
    return {
      body: md.slice(0, match.index),
      key: md.slice(match.index + match[0].length)
    };
  }

  function paperPage(subject, file) {
    var paper = findPaper(subject, file);
    if (!paper) { paint("papers", notFoundHtml()); return; }
    paint("papers", loadingHtml());
    var token = renderToken;
    fetchText(paper.path).then(function (md) {
      if (token !== renderToken) return;
      var split = splitAnswerKey(stripFrontmatter(md));
      var baseDir = dirOf(paper.path);
      var keySection = split.key.trim()
        ? '<div class="keywrap">' +
            '<button type="button" class="pill pill--outline no-print" data-action="toggle-key"' +
              ' data-show="' + esc(t("showKey")) + '" data-hide="' + esc(t("hideKey")) + '">' +
              '<span class="key-toggle-label">' + esc(t("showKey")) + "</span>" +
            "</button>" +
            '<div class="key-body">' +
              labelRow(esc(t("answerKey"))) +
              '<article class="prose">' + renderMarkdown(split.key, baseDir) + "</article>" +
            "</div>" +
          "</div>"
        : "";
      paintView(sectionPaper(
        crumbsHtml([
          { label: t("home"), href: "#/" },
          { label: subject, href: href("subject", subject) },
          { label: t("paper") }
        ]) +
        '<div class="page-head">' +
          '<span class="mono-label page-meta">' + esc(subject) + " · " + esc(t("paper")) + "</span>" +
          '<h1 class="page-title">' + esc(paper.title) + "</h1>" +
          '<div class="page-actions"><button type="button" class="pill pill--acid no-print" data-action="print">' +
            ICONS.print + " " + esc(t("print")) + "</button></div>" +
        "</div>" +
        '<article class="prose">' + renderMarkdown(split.body, baseDir) + "</article>" +
        keySection +
        '<div class="page-actions no-print"><a class="pill pill--outline" href="' + href("subject", subject) + '">' + esc(t("back")) + "</a></div>"
      ));
    }).catch(function (err) {
      console.error("[cairn] paper load failed:", err);
      if (token !== renderToken) return;
      paintView(loadErrorHtml(href("subject", subject)));
    });
  }

  function toggleAnswerKey(button) {
    var wrap = button.closest(".keywrap");
    if (!wrap) return;
    var body = wrap.querySelector(".key-body");
    var label = button.querySelector(".key-toggle-label");
    if (!body) return;
    var open = body.classList.toggle("is-open");
    if (label) label.textContent = open ? button.getAttribute("data-hide") : button.getAttribute("data-show");
  }

  /* ---------------- settings sheet ---------------- */
  function settingsHtml() {
    var currentLang = lang();
    var currentSize = textSize();
    function on(isOn) { return isOn ? " is-on" : ""; }
    return '<button type="button" class="sheet-backdrop" data-action="close-settings" aria-label="' + esc(t("close")) + '"></button>' +
      '<aside class="sheet" role="dialog" aria-modal="true" aria-label="' + esc(t("settings")) + '">' +
        '<div class="sheet-head">' +
          '<span class="sheet-title">' + esc(t("settings")) + "</span>" +
          '<button type="button" class="icon-btn" data-action="close-settings" aria-label="' + esc(t("close")) + '">' + ICONS.close + "</button>" +
        "</div>" +
        '<div class="setting">' +
          '<span class="mono-label">' + esc(t("language")) + "</span>" +
          '<div class="opt-pills">' +
            '<button type="button" class="opt-pill' + on(currentLang === "en") + '" data-action="set-lang" data-value="en">English</button>' +
            '<button type="button" class="opt-pill' + on(currentLang === "ms") + '" data-action="set-lang" data-value="ms">Bahasa Melayu</button>' +
          "</div>" +
        "</div>" +
        '<div class="setting">' +
          '<span class="mono-label">' + esc(t("theme")) + "</span>" +
          '<div class="opt-pills">' +
            '<button type="button" class="opt-pill' + on(theme() === "light") + '" data-action="set-theme" data-value="light">' + esc(t("themeLight")) + "</button>" +
            '<button type="button" class="opt-pill' + on(theme() === "dark") + '" data-action="set-theme" data-value="dark">' + esc(t("themeDark")) + "</button>" +
            '<button type="button" class="opt-pill' + on(theme() === "auto") + '" data-action="set-theme" data-value="auto">' + esc(t("themeAuto")) + "</button>" +
          "</div>" +
        "</div>" +
        '<div class="setting">' +
          '<span class="mono-label">' + esc(t("textSize")) + "</span>" +
          '<div class="opt-pills">' +
            '<button type="button" class="opt-pill' + on(currentSize === "s") + '" data-action="set-size" data-value="s">' + esc(t("sizeS")) + "</button>" +
            '<button type="button" class="opt-pill' + on(currentSize === "m") + '" data-action="set-size" data-value="m">' + esc(t("sizeM")) + "</button>" +
            '<button type="button" class="opt-pill' + on(currentSize === "l") + '" data-action="set-size" data-value="l">' + esc(t("sizeL")) + "</button>" +
          "</div>" +
        "</div>" +
        '<div class="sheet-foot"><span class="mono-label">' + esc(t("moreSoon")) + "</span></div>" +
      "</aside>";
  }
  function renderSettings() {
    layerEl.innerHTML = settingsHtml();
  }
  function openSettings() {
    renderSettings();
    layerEl.classList.add("is-open");
    layerEl.setAttribute("aria-hidden", "false");
  }
  function closeSettings() {
    layerEl.classList.remove("is-open");
    layerEl.setAttribute("aria-hidden", "true");
  }

  /* ---------------- preferences application ---------------- */
  function applyPrefs() {
    document.documentElement.setAttribute("data-textsize", textSize());
    document.documentElement.setAttribute("lang", lang() === "ms" ? "ms" : "en");
    document.documentElement.setAttribute("data-theme", theme());
    var dark = theme() === "dark" ||
      (theme() === "auto" && window.matchMedia &&
       window.matchMedia("(prefers-color-scheme: dark)").matches);
    var meta = document.getElementById("meta-theme");
    if (meta) meta.setAttribute("content", dark ? "#1A1A1D" : "#F9F6F0");
  }

  /* ---------------- render dispatcher ---------------- */
  function render() {
    renderToken += 1;
    quizState = null;
    var current = route();
    switch (current.name) {
      case "home": paint("", homeHtml()); break;
      case "subjects": paint("subjects", subjectsPageHtml()); break;
      case "subject": paint("subjects", subjectPageHtml(current.parts[0] || "")); break;
      case "note": notePage(current.parts[0] || "", current.parts[1] || ""); break;
      case "quizzes": paint("quizzes", quizzesPageHtml()); break;
      case "quiz": quizPage(current.parts[0] || "", current.parts[1] || ""); break;
      case "papers": paint("papers", papersPageHtml()); break;
      case "paper": paperPage(current.parts[0] || "", current.parts[1] || ""); break;
      case "search": paint("", searchPageHtml(current.parts.join("/"))); break;
      default: paint("", notFoundHtml());
    }
  }

  /* ---------------- global event delegation ---------------- */
  document.addEventListener("click", function (event) {
    var target = event.target.closest ? event.target.closest("[data-action]") : null;
    if (!target) return;
    var action = target.getAttribute("data-action");
    if (action === "open-settings") { event.preventDefault(); openSettings(); }
    else if (action === "close-settings") { event.preventDefault(); closeSettings(); }
    else if (action === "set-lang") {
      setPref(PREF_LANG, target.getAttribute("data-value"));
      applyPrefs(); renderSettings(); render();
    }
    else if (action === "set-size") {
      setPref(PREF_SIZE, target.getAttribute("data-value"));
      applyPrefs(); renderSettings();
    }
    else if (action === "set-theme") {
      setPref(PREF_THEME, target.getAttribute("data-value"));
      applyPrefs(); renderSettings();
    }
    else if (action === "quiz-option") handleQuizOption(target);
    else if (action === "toggle-key") toggleAnswerKey(target);
    else if (action === "print") window.print();
    else if (action === "retry-quiz") render();
  });
  document.addEventListener("submit", function (event) {
    var form = event.target.closest ? event.target.closest("form[data-search]") : null;
    if (!form) return;
    event.preventDefault();
    var input = form.querySelector('input[name="q"]');
    var query = input ? input.value.trim() : "";
    if (query) location.hash = "#/search/" + encodeURIComponent(query);
  });
  document.addEventListener("keydown", function (event) {
    if (event.key === "Escape") closeSettings();
  });

  /* ---------------- boot ---------------- */
  function init() {
    appEl = document.getElementById("app");
    layerEl = document.getElementById("settings-layer");
    if (!appEl || !layerEl) {
      console.error("[cairn] required containers missing");
      return;
    }
    applyPrefs();
    window.addEventListener("hashchange", function () {
      closeSettings();
      render();
    });
    loadManifest().then(render);
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
