/* ============================================================
   cairn — client-side engine
   Renders the site from manifest.json (auto-generated by
   scripts/build-manifest.mjs — never hand-edited).
   All content files are treated as UNTRUSTED:
   - Markdown -> marked -> DOMPurify.sanitize before display.
   - Manifest strings -> HTML-escaped before display.
   No study content lives in this file. See CLAUDE.md.
   ============================================================ */
(function () {
  "use strict";

  var CFG = window.SITE_CONFIG || {};
  var V = encodeURIComponent(window.ASSET_V || "1");

  /* ---------------- site chrome translations ---------------- */
  var STRINGS = {
    en: {
      navSubjects: "Subjects", navPapers: "Papers",
      subjects: "Subjects", notes: "Notes", papers: "Exam papers",
      note: "Note", paper: "Paper", home: "Home", back: "Back",
      loading: "Loading", emptyTag: "Status — empty",
      searchPlaceholder: "Search notes, papers…", searchAction: "Search",
      latestNotes: "Latest notes", allSubjects: "All subjects",
      emptyNotesTitle: "No notes yet",
      emptyNotesHint: "Notes appear here automatically the moment a note file is dropped into the content/lectures folder on GitHub.",
      emptyPapersTitle: "No exam papers yet",
      emptyPapersHint: "Exam papers show up here once a Google Drive folder link is added for this subject in config.js.",
      emptySubject: "Nothing here yet",
      notFoundTitle: "Page not found",
      notFoundHint: "This link points to something that does not exist (yet).",
      loadErrorTitle: "Could not load this file",
      loadErrorHint: "The file may have been renamed or removed. Go back and try again.",
      indexErrorTitle: "Site index not ready",
      indexErrorHint: "manifest.json is generated automatically when the site is published on GitHub. Running locally? Run: node scripts/build-manifest.mjs",
      openPapersDrive: "Open exam papers", readNote: "Read note",
      resultsFor: "Results for", foundInNotes: "Found inside notes", searchingNotes: "Searching your notes",
      noResultsTitle: "Nothing found",
      noResultsHint: "Try a shorter word, or check the spelling.",
      settings: "Settings", language: "Language", textSize: "Text size",
      sizeS: "Small", sizeM: "Medium", sizeL: "Large", close: "Close",
      theme: "Appearance", themeLight: "Light", themeDark: "Dark", themeAuto: "Auto",
      disclaimerLabel: "Disclaimer",
      moreSoon: "More options will live here as the site grows.",
      sentTag: "Sent", errorTag: "Error"
    },
    ms: {
      navSubjects: "Subjek", navPapers: "Kertas",
      subjects: "Subjek", notes: "Nota", papers: "Kertas peperiksaan",
      note: "Nota", paper: "Kertas", home: "Utama", back: "Kembali",
      loading: "Memuatkan", emptyTag: "Status — kosong",
      searchPlaceholder: "Cari nota, kertas…", searchAction: "Cari",
      latestNotes: "Nota terkini", allSubjects: "Semua subjek",
      emptyNotesTitle: "Belum ada nota",
      emptyNotesHint: "Nota akan muncul di sini secara automatik sebaik sahaja fail nota diletakkan dalam folder content/lectures di GitHub.",
      emptyPapersTitle: "Belum ada kertas peperiksaan",
      emptyPapersHint: "Kertas peperiksaan akan muncul di sini sebaik sahaja pautan folder Google Drive ditambah untuk subjek ini dalam config.js.",
      emptySubject: "Belum ada apa-apa di sini",
      notFoundTitle: "Halaman tidak dijumpai",
      notFoundHint: "Pautan ini menuju ke sesuatu yang belum wujud.",
      loadErrorTitle: "Fail tidak dapat dimuatkan",
      loadErrorHint: "Fail mungkin telah dinamakan semula atau dipadam. Sila kembali dan cuba lagi.",
      indexErrorTitle: "Indeks laman belum sedia",
      indexErrorHint: "manifest.json dijana secara automatik semasa laman diterbitkan di GitHub. Jalankan secara lokal: node scripts/build-manifest.mjs",
      openPapersDrive: "Buka kertas peperiksaan", readNote: "Baca nota",
      resultsFor: "Hasil carian untuk", foundInNotes: "Dijumpai dalam nota", searchingNotes: "Mencari dalam nota anda",
      noResultsTitle: "Tiada hasil",
      noResultsHint: "Cuba perkataan lebih pendek, atau semak ejaan.",
      settings: "Tetapan", language: "Bahasa", textSize: "Saiz teks",
      sizeS: "Kecil", sizeM: "Sedang", sizeL: "Besar", close: "Tutup",
      theme: "Penampilan", themeLight: "Cerah", themeDark: "Gelap", themeAuto: "Auto",
      disclaimerLabel: "Penafian",
      moreSoon: "Lebih banyak pilihan akan ditambah di sini.",
      sentTag: "Dihantar", errorTag: "Ralat"
    }
  };

  /* ---------------- preferences (Settings sheet) ---------------- */
  var PREF_LANG = "nova.lang";
  var PREF_SIZE = "nova.textsize";
  var PREF_THEME = "nova.theme";
  function getPref(key, fallback) {
    try { return localStorage.getItem(key) || fallback; } catch (err) { return fallback; }
  }
  function setPref(key, value) {
    try { localStorage.setItem(key, value); } catch (err) { /* private mode: ignore */ }
  }
  function lang() {
    var l = getPref(PREF_LANG, CFG.defaultLang || "en");
    return STRINGS[l] ? l : "en";
  }
  function textSize() {
    var s = getPref(PREF_SIZE, "m");
    return ["s", "m", "l"].indexOf(s) >= 0 ? s : "m";
  }
  function theme() {
    var v = getPref(PREF_THEME, "auto");
    return ["light", "dark", "auto"].indexOf(v) >= 0 ? v : "auto";
  }
  function t(key) {
    var table = STRINGS[lang()];
    return (table && table[key]) || STRINGS.en[key] || key;
  }
  function pick(value) {
    if (!value) return "";
    if (typeof value === "string" || Array.isArray(value)) return value;
    return value[lang()] || value.en || "";
  }
  /* Subject DISPLAY names: folder names stay canonical (Malay); when the
     site language is English, word-swap via config.subjectTranslations.
     Routing always uses the canonical name — display only. */
  function subjectLabel(subject) {
    if (lang() === "ms") return String(subject);
    var map = CFG.subjectTranslations || {};
    return Object.keys(map).reduce(function (out, word) {
      return out.replace(new RegExp("\\b" + word + "\\b", "g"), map[word]);
    }, String(subject));
  }

  /* ---------------- tiny helpers ---------------- */
  function esc(value) {
    return String(value == null ? "" : value)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }
  function pad2(n) {
    n = Number(n) || 0;
    return (n < 10 ? "0" : "") + n;
  }
  function dirOf(path) {
    return path.slice(0, path.lastIndexOf("/"));
  }

  var ICONS = {
    arrow: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 8h13M9 3l5 5-5 5"/></svg>',
    search: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="7" cy="7" r="5"/><path d="M11 11l4 4"/></svg>',
    sliders: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M1 4h8M13 4h2M1 12h2M7 12h8"/><circle cx="11" cy="4" r="1.8"/><circle cx="4.5" cy="12" r="1.8"/></svg>',
    close: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M3 3l10 10M13 3L3 13"/></svg>',
    check: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M2.5 8.5l3.5 3.5L13.5 4"/></svg>',
    cross: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 3l10 10M13 3L3 13"/></svg>',
    voice: '<svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round" aria-hidden="true"><path d="M2.5 3.5h11v8H6L2.5 15v-3.5z"/></svg>'
  };

  /* ---------------- manifest state ---------------- */
  var manifest = { subjects: [], notes: [] };
  var manifestFailed = false;
  var renderToken = 0;
  var appEl = null;
  var layerEl = null;

  function normalizeManifest(data) {
    data = data || {};
    return {
      subjects: Array.isArray(data.subjects) ? data.subjects : [],
      notes: Array.isArray(data.notes) ? data.notes : []
    };
  }
  function loadManifest() {
    return fetch("manifest.json?v=" + V, { cache: "no-cache" })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .then(function (data) { manifest = normalizeManifest(data); })
      .catch(function (err) {
        console.error("[cairn] manifest load failed:", err);
        manifest = normalizeManifest(null);
        manifestFailed = true;
      });
  }
  function fetchText(path) {
    return fetch(encodeURI(path) + "?v=" + V, { cache: "no-cache" }).then(function (res) {
      if (!res.ok) throw new Error("HTTP " + res.status);
      return res.text();
    });
  }

  /* ---------------- manifest queries ---------------- */
  function subjectList() {
    var configured = Array.isArray(CFG.subjects) ? CFG.subjects.slice() : [];
    var discovered = manifest.subjects.filter(function (s) {
      return configured.indexOf(s) === -1;
    }).sort();
    return configured.concat(discovered);
  }
  function byDateDesc(a, b) {
    return String(b.sort || "").localeCompare(String(a.sort || "")) ||
           String(a.topic || a.title || "").localeCompare(String(b.topic || b.title || ""));
  }
  /* Natural / numeric-aware compare on filenames, e.g. so "topic-2" sorts
     before "topic-10" instead of after (plain string sort would put "10"
     before "2"). Splits each string into alternating text/number chunks
     and compares number chunks as numbers, text chunks as text. Used to
     list a subject's notes in curriculum order (topic 1, 2, 3…) instead
     of the order they happened to be uploaded in. */
  function naturalCompare(a, b) {
    var re = /(\d+)|(\D+)/g;
    var chunksA = String(a || "").match(re) || [];
    var chunksB = String(b || "").match(re) || [];
    var len = Math.max(chunksA.length, chunksB.length);
    for (var i = 0; i < len; i++) {
      var ca = chunksA[i], cb = chunksB[i];
      if (ca === undefined) return -1;
      if (cb === undefined) return 1;
      var na = /^\d+$/.test(ca), nb = /^\d+$/.test(cb);
      if (na && nb) {
        var diff = parseInt(ca, 10) - parseInt(cb, 10);
        if (diff) return diff;
      } else {
        var cmp = ca.toLowerCase().localeCompare(cb.toLowerCase());
        if (cmp) return cmp;
      }
    }
    return 0;
  }
  /* Filenames are DD-MM-YYYY-topic.md (date first, so they sort sensibly
     on GitHub) — sorting on the raw filename would let that leading
     day/month/year dominate the comparison and just reproduce date order.
     Sort on the note's displayed topic instead (falling back to the
     filename with its date prefix stripped, for the rare note with no
     topic set) — that's also what "Topic 6" vs "Topic 10" numbering
     naturally lives in, since topics are written by hand with the
     chapter/topic number included. */
  function sortNameOf(note) {
    return note.topic || String(note.file || "").replace(/^\d{2}-\d{2}-\d{4}[-\s]*/, "");
  }
  function notesFor(subject) {
    return manifest.notes.filter(function (n) { return n.subject === subject; })
      .sort(function (a, b) { return naturalCompare(sortNameOf(a), sortNameOf(b)); });
  }
  function paperLinkFor(subject) {
    var links = CFG.paperLinks || {};
    var url = links[subject];
    return typeof url === "string" && url.trim() ? url.trim() : "";
  }
  function findNote(subject, file) {
    return manifest.notes.filter(function (n) { return n.subject === subject && n.file === file; })[0];
  }

  /* ---------------- "Talk to us" (private academic help / idea box) ---------------- */
  function voiceEnabled() {
    return !!(CFG.voice && CFG.voice.enabled !== false && CFG.voice.formEndpoints);
  }
  function voiceCopy(kind) {
    return (CFG.voice && CFG.voice[kind]) || {};
  }
  function voiceKindKnown(kind) {
    return kind === "academic" || kind === "idea";
  }

  /* ---------------- markdown (untrusted -> sanitized) ---------------- */
  function stripFrontmatter(src) {
    var match = /^﻿?\s*---[^\n]*\n[\s\S]*?\n---[^\n]*\n?/.exec(src);
    return match ? src.slice(match[0].length) : src;
  }
  function fixRelativeMedia(html, baseDir) {
    var tpl = document.createElement("template");
    tpl.innerHTML = html;
    var images = tpl.content.querySelectorAll("img[src]");
    for (var i = 0; i < images.length; i++) {
      var src = images[i].getAttribute("src") || "";
      if (!/^(https?:|data:|\/|#)/i.test(src)) {
        images[i].setAttribute("src", baseDir + "/" + src);
      }
    }
    return tpl.innerHTML;
  }

  /* ---------------- math (LaTeX -> KaTeX) ----------------
     Notes/papers write math the standard way: $$...$$ for a display
     (block) equation, $...$ for inline. marked knows nothing about
     LaTeX, so left alone it would mangle "_" / "\" / "*" inside math
     as markdown syntax and print the raw source as text (the bug this
     fixes). Instead we pull every math span OUT of the markdown text
     before marked ever sees it, drop in a plain alphanumeric token
     that marked can't misinterpret, and after marked + DOMPurify have
     produced safe HTML, swap the tokens back for KaTeX-rendered
     equations. KaTeX runs with trust:false + strict:"ignore", which
     is its own sanitized mode for untrusted LaTeX (disables \href,
     \includegraphics, etc.) — matching the "content is untrusted"
     rule above without needing DOMPurify to also understand KaTeX's
     SVG/MathML output. */
  function renderMathToHtml(expr, displayMode) {
    if (!window.katex) return esc(expr);
    try {
      return window.katex.renderToString(expr, {
        throwOnError: false,
        displayMode: displayMode,
        strict: "ignore",
        trust: false
      });
    } catch (err) {
      console.error("[cairn] katex render failed:", err);
      return '<code class="math-error">' + esc(expr) + "</code>";
    }
  }
  function extractMath(src) {
    var nonce = Math.random().toString(36).slice(2, 8);
    var store = [];
    function stash(expr, displayMode) {
      var token = "zktoken" + nonce + store.length + "zk";
      store.push(renderMathToHtml(expr.trim(), displayMode));
      return token;
    }
    // Display math first ($$...$$), so its inner $ signs can't be
    // misread as inline math delimiters. Neither pattern crosses a
    // blank line, matching how every note in content/ writes math.
    var out = src.replace(/\$\$([^\n]+?)\$\$/g, function (_, expr) {
      return stash(expr, true);
    });
    out = out.replace(/\$([^\$\n]+?)\$/g, function (_, expr) {
      return stash(expr, false);
    });
    return { text: out, store: store, nonce: nonce };
  }
  function restoreMath(html, extracted) {
    var re = new RegExp("zktoken" + extracted.nonce + "(\\d+)zk", "g");
    return html.replace(re, function (_, i) {
      return extracted.store[Number(i)] || "";
    });
  }
  function renderMarkdown(src, baseDir) {
    if (!window.marked || !window.DOMPurify) {
      console.error("[cairn] marked/DOMPurify not loaded");
      return "<p>" + esc(t("loadErrorHint")) + "</p>";
    }
    var extracted = extractMath(src);
    var raw = window.marked.parse(extracted.text, { gfm: true, breaks: true, async: false });
    var clean = window.DOMPurify.sanitize(raw, { USE_PROFILES: { html: true } });
    var withMath = restoreMath(clean, extracted);
    return fixRelativeMedia(withMath, baseDir);
  }

  /* ---------------- routing ---------------- */
  function route() {
    var hash = location.hash.replace(/^#\/?/, "");
    if (!hash) return { name: "home", parts: [] };
    var parts = hash.split("/").map(function (part) {
      try { return decodeURIComponent(part); } catch (err) { return part; }
    });
    return { name: parts[0] || "home", parts: parts.slice(1) };
  }
  function href() {
    var parts = Array.prototype.slice.call(arguments);
    return "#/" + parts.map(encodeURIComponent).join("/");
  }

  /* ---------------- chrome (header / footer / shells) ---------------- */
  function headerHtml(active) {
    function cls(name) { return active === name ? ' class="is-active"' : ""; }
    return '<header class="site-head">' +
      '<div class="wrap">' +
        '<a class="brand" href="#/">' + esc(CFG.siteName || "cairn") + "</a>" +
        '<nav class="site-nav" aria-label="Main">' +
          '<a href="' + href("subjects") + '"' + cls("subjects") + ">" + esc(t("navSubjects")) + "</a>" +
          '<a href="' + href("papers") + '"' + cls("papers") + ">" + esc(t("navPapers")) + "</a>" +
          (voiceEnabled() ? '<a href="' + href("voice") + '"' + cls("voice") + ">" + esc(pick(CFG.voice.navLabel)) + "</a>" : "") +
        "</nav>" +
        '<button type="button" class="icon-btn" data-action="open-settings" aria-label="' + esc(t("settings")) + '">' +
          ICONS.sliders +
        "</button>" +
      "</div></header>";
  }
  function footerHtml() {
    var analyticsLine = (CFG.analyticsId && String(CFG.analyticsId).trim())
      ? '<p class="foot-analytics">' + esc(pick(CFG.analyticsNote)) + "</p>"
      : "";
    return '<footer class="site-foot">' +
      '<div class="wrap">' +
        '<div class="foot-brand">' + esc(CFG.siteName || "cairn") + '<span class="dot">.</span></div>' +
        '<p class="foot-disclaimer"><span class="mono-label">' + esc(t("disclaimerLabel")) + " — </span>" +
          esc(pick(CFG.disclaimer)) + "</p>" +
        analyticsLine +
        '<div class="foot-meta">' +
          '<span class="foot-tag">' + esc(CFG.siteName || "cairn") + " · static archive · github pages</span>" +
          '<button type="button" class="mono-label" data-action="open-settings">' + esc(t("settings")) + "</button>" +
        "</div>" +
      "</div></footer>";
  }
  function paint(active, mainHtml) {
    appEl.innerHTML = headerHtml(active) + '<main id="view">' + mainHtml + "</main>" + footerHtml();
    window.scrollTo(0, 0);
  }
  function paintView(html) {
    var view = document.getElementById("view");
    if (view) view.innerHTML = html;
  }
  function sectionPaper(inner) {
    return '<section class="sec sec--paper"><div class="wrap">' + inner + "</div></section>";
  }
  function crumbsHtml(items) {
    var parts = items.map(function (item) {
      return item.href
        ? '<a href="' + item.href + '">' + esc(item.label) + "</a>"
        : "<span>" + esc(item.label) + "</span>";
    });
    return '<nav class="crumbs" aria-label="Breadcrumb">' + parts.join('<span class="sep">/</span>') + "</nav>";
  }
  function labelRow(left, right) {
    return '<div class="label-row"><span class="mono-label">' + left + "</span>" +
      (right != null ? '<span class="mono-label">' + right + "</span>" : "") + "</div>";
  }
  function emptyBoxRaw(tag, title, hint, extra, modifier) {
    return '<div class="empty' + (modifier ? " empty--" + modifier : "") + '">' +
      '<span class="mono-label">' + esc(tag) + "</span>" +
      '<div class="empty-title">' + esc(title) + "</div>" +
      '<p class="empty-hint">' + esc(hint) + "</p>" +
      (extra || "") +
    "</div>";
  }
  function emptyBox(titleKey, hintKey) {
    return emptyBoxRaw(t("emptyTag"), t(titleKey), t(hintKey));
  }
  function loadingHtml() {
    return sectionPaper('<span class="mono-label">' + esc(t("loading")) + " …</span>");
  }
  function notFoundHtml() {
    return sectionPaper(
      crumbsHtml([{ label: t("home"), href: "#/" }]) +
      '<div class="empty">' +
        '<span class="mono-label">404</span>' +
        '<div class="empty-title">' + esc(t("notFoundTitle")) + "</div>" +
        '<p class="empty-hint">' + esc(t("notFoundHint")) + "</p>" +
        '<a class="pill pill--acid" href="#/">' + esc(t("home")) + "</a>" +
      "</div>"
    );
  }
  function loadErrorHtml(backHref) {
    return sectionPaper(
      '<div class="empty">' +
        '<span class="mono-label">' + esc(t("emptyTag")) + "</span>" +
        '<div class="empty-title">' + esc(t("loadErrorTitle")) + "</div>" +
        '<p class="empty-hint">' + esc(t("loadErrorHint")) + "</p>" +
        '<a class="pill pill--acid" href="' + backHref + '">' + esc(t("back")) + "</a>" +
      "</div>"
    );
  }

  /* ---------------- shared list pieces ---------------- */
  function noteRow(note, index) {
    return '<a class="row" href="' + href("note", note.subject, note.file) + '">' +
      '<span class="row-num">' + pad2(index + 1) + "</span>" +
      '<span class="row-main">' +
        '<span class="mono-label row-meta">' + esc(subjectLabel(note.subject)) +
          (note.date ? " · " + esc(note.date) : "") + " · " + esc(t("note")) + "</span>" +
        '<span class="row-title">' + esc(note.topic) + "</span>" +
        (note.summary ? '<span class="row-sub">' + esc(note.summary) + "</span>" : "") +
      "</span>" +
      '<span class="row-end"><span class="row-arrow">' + ICONS.arrow + "</span></span>" +
    "</a>";
  }
  /* Papers are no longer individual files on this site — each subject
     with a link configured (config.js: paperLinks) gets one button that
     opens that subject's Google Drive folder in a new tab. */
  function papersButtonHtml(subject) {
    var url = paperLinkFor(subject);
    if (!url) return emptyBox("emptyPapersTitle", "emptyPapersHint");
    return '<a class="pill pill--acid papers-drive-btn" href="' + esc(url) + '" target="_blank" rel="noopener">' +
      esc(subjectLabel(subject)) + " — " + esc(t("openPapersDrive")) + " " + ICONS.arrow +
    "</a>";
  }
  function searchFormHtml(prefill) {
    return '<form class="search-form" data-search role="search">' +
      '<input class="search-input" type="search" name="q" value="' + esc(prefill || "") + '"' +
        ' placeholder="' + esc(t("searchPlaceholder")) + '" aria-label="' + esc(t("searchAction")) + '">' +
      '<button class="search-btn" type="submit" aria-label="' + esc(t("searchAction")) + '">' + ICONS.search + "</button>" +
    "</form>";
  }

  /* ---------------- views ---------------- */
  function homeHtml() {
    var subjects = subjectList();
    var latest = manifest.notes.slice().sort(byDateDesc).slice(0, 6);
    var lines = pick(CFG.heroLines);
    if (!Array.isArray(lines)) lines = [];
    var year = new Date().getFullYear();

    var hero = '<section class="sec--ink hero-sec">' +
      '<div class="wrap">' +
        '<div class="hero-kicker">' +
          '<span class="mono-label">' + esc(pick(CFG.heroKicker)) + "</span>" +
          '<span class="mono-label">Vol. 02 — ' + year + "</span>" +
        "</div>" +
        '<h1 class="wordmark">' + esc(CFG.siteName || "cairn") + '<span class="dot">.</span></h1>' +
        '<div class="statement">' +
          lines.map(function (line) {
            return '<span class="statement-line">' + esc(line) + "</span>";
          }).join("") +
        "</div>" +
      "</div></section>";

    var banner = '<section class="sec--acid banner"><div class="wrap">' +
      '<span class="mono-label">' + esc(t("disclaimerLabel")) + "</span>" +
      '<p class="banner-text">' + esc(pick(CFG.disclaimer)) + "</p>" +
    "</div></section>";

    var voiceBanner = voiceEnabled()
      ? '<section class="sec sec--paper sec--tight"><div class="wrap">' +
          '<a class="voice-banner" href="' + href("voice") + '">' +
            '<span class="mono-label">' + esc(pick(CFG.voice.bannerKicker)) + "</span>" +
            '<span class="voice-banner-heading">' + esc(pick(CFG.voice.bannerHeading)) + "</span>" +
            '<span class="voice-banner-text">' + esc(pick(CFG.voice.bannerText)) + "</span>" +
            '<span class="voice-banner-cta"><span class="mono-label">' + esc(pick(CFG.voice.bannerCta)) + "</span>" + ICONS.arrow + "</span>" +
          "</a>" +
        "</div></section>"
      : "";

    var search = '<section class="sec sec--paper sec--tight"><div class="wrap">' +
      searchFormHtml("") +
    "</div></section>";

    var indexWarning = manifestFailed
      ? '<section class="sec sec--paper sec--tight"><div class="wrap">' + emptyBox("indexErrorTitle", "indexErrorHint") + "</div></section>"
      : "";

    var latestSection = '<section class="sec sec--paper"><div class="wrap">' +
      labelRow(esc(t("latestNotes")), pad2(latest.length)) +
      (latest.length
        ? '<div class="card-grid">' + latest.map(function (note) {
            return '<a class="card" href="' + href("note", note.subject, note.file) + '">' +
              '<span class="mono-label">' + esc(subjectLabel(note.subject)) + (note.date ? " · " + esc(note.date) : "") + "</span>" +
              '<span class="card-title">' + esc(note.topic) + "</span>" +
              (note.summary ? '<span class="card-sub">' + esc(note.summary) + "</span>" : "") +
              '<span class="card-foot"><span class="mono-label">' + esc(t("readNote")) + "</span>" + ICONS.arrow + "</span>" +
            "</a>";
          }).join("") + "</div>"
        : emptyBox("emptyNotesTitle", "emptyNotesHint")) +
    "</div></section>";

    var subjectsSection = '<section class="sec sec--paper" style="padding-top:0"><div class="wrap">' +
      labelRow(esc(t("allSubjects")), pad2(subjects.length)) +
      subjectRowsHtml(subjects) +
    "</div></section>";

    return hero + banner + search + indexWarning + latestSection + subjectsSection + voiceBanner;
  }

  function subjectRowsHtml(subjects) {
    return '<div class="index-rows">' + subjects.map(function (subject, i) {
      var n = notesFor(subject).length;
      var hasPapers = !!paperLinkFor(subject);
      var parts = [];
      if (n) parts.push(n + " " + t("notes").toLowerCase());
      if (hasPapers) parts.push(t("papers").toLowerCase());
      var counts = parts.length ? esc(parts.join(" · ")) : esc(t("emptySubject"));
      return '<a class="row" href="' + href("subject", subject) + '">' +
        '<span class="row-num">' + pad2(i + 1) + "</span>" +
        '<span class="row-main">' +
          '<span class="row-title">' + esc(subjectLabel(subject)) + "</span>" +
          '<span class="row-sub">' + counts + "</span>" +
        "</span>" +
        '<span class="row-end"><span class="row-arrow">' + ICONS.arrow + "</span></span>" +
      "</a>";
    }).join("") + "</div>";
  }

  function subjectsPageHtml() {
    return sectionPaper(
      crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("subjects") }]) +
      '<div class="page-head"><h1 class="page-title page-title--sans">' + esc(t("subjects")) + "</h1></div>" +
      subjectRowsHtml(subjectList())
    );
  }

  function subjectPageHtml(subject) {
    var known = subjectList().indexOf(subject) !== -1;
    if (!known) return notFoundHtml();
    var notes = notesFor(subject);
    var body =
      crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("subjects"), href: href("subjects") }, { label: subjectLabel(subject) }]) +
      '<div class="page-head">' +
        '<h1 class="page-title page-title--sans">' + esc(subjectLabel(subject)) + "</h1>" +
      "</div>" +
      '<div class="stack">' +
        labelRow(esc(t("notes")), pad2(notes.length)) +
        (notes.length
          ? '<div class="index-rows">' + notes.map(noteRow).join("") + "</div>"
          : emptyBox("emptyNotesTitle", "emptyNotesHint")) +
        labelRow(esc(t("papers"))) +
        papersButtonHtml(subject) +
      "</div>";
    return sectionPaper(body);
  }

  function papersPageHtml() {
    var subjects = subjectList();
    var linked = subjects.filter(function (s) { return !!paperLinkFor(s); });
    var body = crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("papers") }]) +
      '<div class="page-head"><h1 class="page-title page-title--sans">' + esc(t("papers")) + "</h1></div>";
    if (!linked.length) return sectionPaper(body + emptyBox("emptyPapersTitle", "emptyPapersHint"));
    var buttons = '<div class="papers-drive-list">' +
      linked.map(function (s) { return papersButtonHtml(s); }).join("") +
    "</div>";
    return sectionPaper(body + buttons);
  }

  /* Full-text search inside note bodies. The manifest only carries
     title/summary, not content, so matching INSIDE a note means actually
     fetching it. We fetch each note's text once (only the notes not
     already searched this visit) and cache the cleaned-up plain text, so
     repeat searches are instant after the first one. Results come back
     in two waves: title/subject/summary matches render immediately (no
     fetch needed), then content matches fill in once their files load. */
  var noteBodyCache = {};

  /* Strip the frontmatter block, then knock down common Markdown syntax
     (headings, bold/italic, links, code fences, list bullets, table
     pipes) so search snippets read as plain sentences instead of raw
     Markdown. Not a full parser — just enough for clean-looking snippets. */
  function plainifyMarkdown(md) {
    return stripFrontmatter(md)
      .replace(/```[\s\S]*?```/g, " ")
      .replace(/`([^`]*)`/g, "$1")
      .replace(/!\[[^\]]*\]\([^)]*\)/g, " ")
      .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
      .replace(/^#{1,6}\s*/gm, "")
      .replace(/[*_]{1,3}([^*_]+)[*_]{1,3}/g, "$1")
      .replace(/^\s*[-*+]\s+/gm, "")
      .replace(/\|/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }
  function fetchNoteBody(note) {
    if (Object.prototype.hasOwnProperty.call(noteBodyCache, note.path)) {
      return Promise.resolve(noteBodyCache[note.path]);
    }
    return fetchText(note.path)
      .then(function (md) { return (noteBodyCache[note.path] = plainifyMarkdown(md)); })
      .catch(function () { return (noteBodyCache[note.path] = ""); });
  }
  function snippetAround(text, needle, radius) {
    var idx = text.toLowerCase().indexOf(needle);
    if (idx === -1) return "";
    var start = Math.max(0, idx - radius);
    var end = Math.min(text.length, idx + needle.length + radius);
    return (start > 0 ? "…" : "") + text.slice(start, end).trim() + (end < text.length ? "…" : "");
  }
  function highlightSnippet(snippet, needle) {
    var idx = snippet.toLowerCase().indexOf(needle.toLowerCase());
    if (idx === -1) return esc(snippet);
    return esc(snippet.slice(0, idx)) + "<mark>" + esc(snippet.slice(idx, idx + needle.length)) + "</mark>" +
      esc(snippet.slice(idx + needle.length));
  }
  function noteContentRow(hit, index) {
    var note = hit.note;
    return '<a class="row" href="' + href("note", note.subject, note.file) + '">' +
      '<span class="row-num">' + pad2(index + 1) + "</span>" +
      '<span class="row-main">' +
        '<span class="mono-label row-meta">' + esc(subjectLabel(note.subject)) + (note.date ? " · " + esc(note.date) : "") + "</span>" +
        '<span class="row-title">' + esc(note.topic) + "</span>" +
        '<span class="row-sub search-snippet">' + hit.snippetHtml + "</span>" +
      "</span>" +
      '<span class="row-end"><span class="row-arrow">' + ICONS.arrow + "</span></span>" +
    "</a>";
  }

  function searchResultsHtml(query, metaHits, contentHits, paperHits, scanning) {
    var total = metaHits.length + contentHits.length + paperHits.length;
    var body = crumbsHtml([{ label: t("home"), href: "#/" }, { label: t("searchAction") }]) +
      '<div class="page-head">' +
        '<span class="mono-label page-meta">' + esc(t("resultsFor")) + " “" + esc(query) + "” — " + pad2(total) + "</span>" +
        searchFormHtml(query) +
      "</div>";

    if (!total && !scanning) {
      return sectionPaper(body +
        '<div class="empty">' +
          '<span class="mono-label">' + esc(t("emptyTag")) + "</span>" +
          '<div class="empty-title">' + esc(t("noResultsTitle")) + "</div>" +
          '<p class="empty-hint">' + esc(t("noResultsHint")) + "</p>" +
        "</div>");
    }
    var out = "";
    if (metaHits.length) out += labelRow(esc(t("notes")), pad2(metaHits.length)) + '<div class="index-rows">' + metaHits.map(noteRow).join("") + "</div>";
    if (contentHits.length) out += labelRow(esc(t("foundInNotes")), pad2(contentHits.length)) + '<div class="index-rows">' + contentHits.map(noteContentRow).join("") + "</div>";
    if (scanning) out += '<div class="search-scanning"><span class="mono-label">' + esc(t("searchingNotes")) + " …</span></div>";
    if (paperHits.length) out += labelRow(esc(t("papers")), pad2(paperHits.length)) + '<div class="papers-drive-list">' + paperHits.map(function (s) { return papersButtonHtml(s); }).join("") + "</div>";
    return sectionPaper(body + '<div class="stack">' + out + "</div>");
  }

  function searchPage(query) {
    var needle = String(query || "").trim().toLowerCase();
    function hit(value) { return String(value || "").toLowerCase().indexOf(needle) !== -1; }
    var metaHits = needle ? manifest.notes.filter(function (n) { return hit(n.subject) || hit(subjectLabel(n.subject)) || hit(n.topic) || hit(n.summary); }) : [];
    var paperHits = needle ? subjectList().filter(function (s) { return !!paperLinkFor(s) && (hit(s) || hit(subjectLabel(s))); }) : [];

    if (!needle) { paint("", searchResultsHtml(query, [], [], [], false)); return; }

    var matched = {};
    metaHits.forEach(function (n) { matched[n.path] = true; });
    var candidates = manifest.notes.filter(function (n) { return !matched[n.path]; });

    var token = renderToken;
    if (!candidates.length) { paint("", searchResultsHtml(query, metaHits, [], paperHits, false)); return; }

    paint("", searchResultsHtml(query, metaHits, [], paperHits, true));
    Promise.all(candidates.map(function (n) {
      return fetchNoteBody(n).then(function (body) {
        return body.toLowerCase().indexOf(needle) === -1
          ? null
          : { note: n, snippetHtml: highlightSnippet(snippetAround(body, needle, 60), needle) };
      });
    })).then(function (results) {
      if (token !== renderToken) return;
      paintView(searchResultsHtml(query, metaHits, results.filter(Boolean), paperHits, false));
    });
  }

  /* ---------------- note view (async fetch) ---------------- */
  function notePage(subject, file) {
    var note = findNote(subject, file);
    if (!note) { paint("subjects", notFoundHtml()); return; }
    paint("subjects", loadingHtml());
    var token = renderToken;
    fetchText(note.path).then(function (md) {
      if (token !== renderToken) return;
      var html = renderMarkdown(stripFrontmatter(md), dirOf(note.path));
      paintView(sectionPaper(
        crumbsHtml([
          { label: t("home"), href: "#/" },
          { label: subjectLabel(subject), href: href("subject", subject) },
          { label: t("note") }
        ]) +
        '<div class="page-head">' +
          '<span class="mono-label page-meta">' + esc(subjectLabel(subject)) +
            (note.date ? " · " + esc(note.date) : "") + " · " + esc(t("note")) + "</span>" +
          '<h1 class="page-title">' + esc(note.topic) + "</h1>" +
          (note.summary ? '<p class="page-sub">' + esc(note.summary) + "</p>" : "") +
        "</div>" +
        '<article class="prose">' + html + "</article>" +
        '<div class="page-actions"><a class="pill pill--outline" href="' + href("subject", subject) + '">' + esc(t("back")) + "</a></div>"
      ));
    }).catch(function (err) {
      console.error("[cairn] note load failed:", err);
      if (token !== renderToken) return;
      paintView(loadErrorHtml(href("subject", subject)));
    });
  }

  /* ---------------- "Talk to us" view (private form -> Formspree) ---------------- */
  function voicePageHtml(kind) {
    if (!voiceEnabled()) return notFoundHtml();
    if (!kind) return voiceLandingHtml();
    if (!voiceKindKnown(kind)) return notFoundHtml();
    return voiceFormHtml(kind);
  }

  function voiceEntryCard(kind) {
    var c = voiceCopy(kind);
    return '<a class="card" href="' + href("voice", kind) + '">' +
      '<span class="card-title">' + esc(pick(c.cardTitle)) + "</span>" +
      '<span class="card-sub">' + esc(pick(c.cardDesc)) + "</span>" +
      '<span class="card-foot"><span class="mono-label">' + esc(pick(c.cardCta)) + "</span>" + ICONS.arrow + "</span>" +
    "</a>";
  }

  function voiceLandingHtml() {
    var v = CFG.voice;
    return sectionPaper(
      crumbsHtml([{ label: t("home"), href: "#/" }, { label: pick(v.navLabel) }]) +
      '<div class="page-head">' +
        '<h1 class="page-title page-title--sans">' + esc(pick(v.introHeading)) + "</h1>" +
        (pick(v.introText) ? '<p class="page-sub">' + esc(pick(v.introText)) + "</p>" : "") +
      "</div>" +
      '<div class="callout">' + esc(pick(v.confidentialNote)) + "</div>" +
      '<div class="card-grid voice-cards">' + voiceEntryCard("academic") + voiceEntryCard("idea") + "</div>"
    );
  }

  function voiceFormHtml(kind) {
    var v = CFG.voice;
    var c = voiceCopy(kind);
    var endpoint = v.formEndpoints[kind];
    var crumbs = crumbsHtml([
      { label: t("home"), href: "#/" },
      { label: pick(v.navLabel), href: href("voice") },
      { label: pick(c.cardTitle) }
    ]);
    if (!endpoint) {
      // Owner hasn't set this endpoint in config.js yet — fail gracefully
      // instead of showing a form with nowhere to send.
      return sectionPaper(crumbs + emptyBoxRaw(t("errorTag"), pick(c.formHeading), pick(v.errorText)));
    }
    var subjectField = kind === "academic"
      ? '<div class="field">' +
          '<label for="voice-subject">' + esc(pick(c.subjectLabel)) + "</label>" +
          '<select class="field-select" id="voice-subject" name="subject">' +
            '<option value="">' + esc(pick(c.subjectNoneOption)) + "</option>" +
            subjectList().map(function (s) {
              return '<option value="' + esc(s) + '">' + esc(subjectLabel(s)) + "</option>";
            }).join("") +
          "</select>" +
        "</div>"
      : "";
    var mailSubject = "Nova — " + (kind === "academic" ? "Academic help" : "General vent");
    return sectionPaper(
      crumbs +
      '<div class="page-head">' +
        '<h1 class="page-title page-title--sans">' + esc(pick(c.formHeading)) + "</h1>" +
        (pick(c.formIntro) ? '<p class="page-sub">' + esc(pick(c.formIntro)) + "</p>" : "") +
      "</div>" +
      '<div class="callout">' + esc(pick(v.confidentialNote)) + "</div>" +
      '<form class="voice-form" data-voice-form data-kind="' + esc(kind) + '" action="' + esc(endpoint) + '" method="POST">' +
        '<input type="hidden" name="_subject" value="' + esc(mailSubject) + '">' +
        '<input class="hp-field" type="text" name="_gotcha" tabindex="-1" autocomplete="off" aria-hidden="true">' +
        subjectField +
        '<div class="field">' +
          '<label for="voice-message">' + esc(pick(c.promptLabel)) + "</label>" +
          '<textarea class="field-textarea" id="voice-message" name="message" required placeholder="' + esc(pick(c.promptPlaceholder)) + '"></textarea>' +
        "</div>" +
        '<div class="field">' +
          '<label for="voice-contact">' + esc(pick(v.contactLabel)) + "</label>" +
          '<input class="field-input" type="text" id="voice-contact" name="contact" placeholder="' + esc(pick(v.contactPlaceholder)) + '">' +
        "</div>" +
        '<div class="page-actions">' +
          '<button type="submit" class="pill pill--acid">' + esc(pick(v.submitLabel)) + "</button>" +
          '<a class="pill pill--outline" href="' + href("voice") + '">' + esc(t("back")) + "</a>" +
        "</div>" +
      "</form>"
    );
  }

  function voiceThanksHtml(kind) {
    var v = CFG.voice, c = voiceCopy(kind);
    return sectionPaper(
      crumbsHtml([{ label: t("home"), href: "#/" }, { label: pick(v.navLabel), href: href("voice") }]) +
      emptyBoxRaw(t("sentTag"), pick(c.thanksHeading), pick(c.thanksText),
        '<a class="pill pill--outline" href="#/">' + esc(t("home")) + "</a>", "success")
    );
  }

  function voiceErrorHtml(kind) {
    var v = CFG.voice;
    return sectionPaper(
      crumbsHtml([{ label: t("home"), href: "#/" }, { label: pick(v.navLabel), href: href("voice") }]) +
      emptyBoxRaw(t("errorTag"), pick(v.errorHeading), pick(v.errorText),
        '<button type="button" class="pill pill--acid" data-action="retry-voice" data-kind="' + esc(kind) + '">' + esc(t("retry")) + "</button>")
    );
  }

  function handleVoiceSubmit(form) {
    var kind = form.getAttribute("data-kind");
    var btn = form.querySelector('button[type="submit"]');
    if (btn) { btn.disabled = true; btn.textContent = pick(CFG.voice.sendingLabel); }
    var token = renderToken;
    fetch(form.getAttribute("action"), {
      method: "POST",
      body: new FormData(form),
      headers: { Accept: "application/json" }
    }).then(function (res) {
      if (token !== renderToken) return;
      if (res.ok) paintView(voiceThanksHtml(kind));
      else paintView(voiceErrorHtml(kind));
    }).catch(function (err) {
      console.error("[cairn] voice submit failed:", err);
      if (token !== renderToken) return;
      paintView(voiceErrorHtml(kind));
    });
  }

  /* ---------------- settings sheet ---------------- */
  function settingsHtml() {
    var currentLang = lang();
    var currentSize = textSize();
    function on(isOn) { return isOn ? " is-on" : ""; }
    return '<button type="button" class="sheet-backdrop" data-action="close-settings" aria-label="' + esc(t("close")) + '"></button>' +
      '<aside class="sheet" role="dialog" aria-modal="true" aria-label="' + esc(t("settings")) + '">' +
        '<div class="sheet-head">' +
          '<span class="sheet-title">' + esc(t("settings")) + "</span>" +
          '<button type="button" class="icon-btn" data-action="close-settings" aria-label="' + esc(t("close")) + '">' + ICONS.close + "</button>" +
        "</div>" +
        '<div class="setting">' +
          '<span class="mono-label">' + esc(t("language")) + "</span>" +
          '<div class="opt-pills">' +
            '<button type="button" class="opt-pill' + on(currentLang === "en") + '" data-action="set-lang" data-value="en">English</button>' +
            '<button type="button" class="opt-pill' + on(currentLang === "ms") + '" data-action="set-lang" data-value="ms">Bahasa Melayu</button>' +
          "</div>" +
        "</div>" +
        '<div class="setting">' +
          '<span class="mono-label">' + esc(t("theme")) + "</span>" +
          '<div class="opt-pills">' +
            '<button type="button" class="opt-pill' + on(theme() === "light") + '" data-action="set-theme" data-value="light">' + esc(t("themeLight")) + "</button>" +
            '<button type="button" class="opt-pill' + on(theme() === "dark") + '" data-action="set-theme" data-value="dark">' + esc(t("themeDark")) + "</button>" +
            '<button type="button" class="opt-pill' + on(theme() === "auto") + '" data-action="set-theme" data-value="auto">' + esc(t("themeAuto")) + "</button>" +
          "</div>" +
        "</div>" +
        '<div class="setting">' +
          '<span class="mono-label">' + esc(t("textSize")) + "</span>" +
          '<div class="opt-pills">' +
            '<button type="button" class="opt-pill' + on(currentSize === "s") + '" data-action="set-size" data-value="s">' + esc(t("sizeS")) + "</button>" +
            '<button type="button" class="opt-pill' + on(currentSize === "m") + '" data-action="set-size" data-value="m">' + esc(t("sizeM")) + "</button>" +
            '<button type="button" class="opt-pill' + on(currentSize === "l") + '" data-action="set-size" data-value="l">' + esc(t("sizeL")) + "</button>" +
          "</div>" +
        "</div>" +
        '<div class="sheet-foot"><span class="mono-label">' + esc(t("moreSoon")) + "</span></div>" +
      "</aside>";
  }
  function renderSettings() {
    layerEl.innerHTML = settingsHtml();
  }
  function openSettings() {
    renderSettings();
    layerEl.classList.add("is-open");
    layerEl.setAttribute("aria-hidden", "false");
  }
  function closeSettings() {
    layerEl.classList.remove("is-open");
    layerEl.setAttribute("aria-hidden", "true");
  }

  /* ---------------- preferences application ---------------- */
  function applyPrefs() {
    document.documentElement.setAttribute("data-textsize", textSize());
    document.documentElement.setAttribute("lang", lang() === "ms" ? "ms" : "en");
    document.documentElement.setAttribute("data-theme", theme());
    var dark = theme() === "dark" ||
      (theme() === "auto" && window.matchMedia &&
       window.matchMedia("(prefers-color-scheme: dark)").matches);
    var meta = document.getElementById("meta-theme");
    if (meta) meta.setAttribute("content", dark ? "#1A1A1D" : "#F9F6F0");
  }

  /* ---------------- page title (browser tab + GA page_title) ----------------
     The tab title used to always say "NOVA — study notes" no matter what
     page you were on, since this is one HTML page that never reloads. That
     also meant Google Analytics' "Pages and screens" report couldn't tell
     pages apart by title (only by the #/... path). Set a real per-page
     title here, before anything paints — trackPageview() below reads
     document.title, so this has to run first. */
  function pageTitleFor(current) {
    var parts = current.parts;
    switch (current.name) {
      case "home": return "";
      case "subjects": return t("subjects");
      case "subject": {
        var subject = parts[0] || "";
        return subjectList().indexOf(subject) === -1 ? t("notFoundTitle") : subjectLabel(subject);
      }
      case "note": {
        var note = findNote(parts[0] || "", parts[1] || "");
        return note ? note.topic : t("notFoundTitle");
      }
      case "papers": return t("papers");
      case "voice": {
        var kind = parts[0];
        if (!kind) return voiceEnabled() ? pick(CFG.voice.navLabel) : t("notFoundTitle");
        if (!voiceKindKnown(kind)) return t("notFoundTitle");
        return pick(voiceCopy(kind).cardTitle) || pick(CFG.voice.navLabel);
      }
      case "search": {
        var query = parts.join("/");
        return query ? t("searchAction") + ": " + query : t("searchAction");
      }
      default: return t("notFoundTitle");
    }
  }
  function setDocumentTitle(current) {
    var site = CFG.siteName || "NOVA";
    var pageTitle = pageTitleFor(current);
    document.title = pageTitle ? pageTitle + " · " + site : site + " — study notes";
  }

  /* ---------------- render dispatcher ---------------- */
  function render() {
    renderToken += 1;
    var current = route();
    setDocumentTitle(current);
    switch (current.name) {
      case "home": paint("", homeHtml()); break;
      case "subjects": paint("subjects", subjectsPageHtml()); break;
      case "subject": paint("subjects", subjectPageHtml(current.parts[0] || "")); break;
      case "note": notePage(current.parts[0] || "", current.parts[1] || ""); break;
      case "papers": paint("papers", papersPageHtml()); break;
      case "voice": paint("voice", voicePageHtml(current.parts[0] || "")); break;
      case "search": searchPage(current.parts.join("/")); break;
      default: paint("", notFoundHtml());
    }
    trackPageview(current);
  }

  /* ---------------- global event delegation ---------------- */
  document.addEventListener("click", function (event) {
    var target = event.target.closest ? event.target.closest("[data-action]") : null;
    if (!target) return;
    var action = target.getAttribute("data-action");
    if (action === "open-settings") { event.preventDefault(); openSettings(); }
    else if (action === "close-settings") { event.preventDefault(); closeSettings(); }
    else if (action === "set-lang") {
      setPref(PREF_LANG, target.getAttribute("data-value"));
      applyPrefs(); renderSettings(); render();
    }
    else if (action === "set-size") {
      setPref(PREF_SIZE, target.getAttribute("data-value"));
      applyPrefs(); renderSettings();
    }
    else if (action === "set-theme") {
      setPref(PREF_THEME, target.getAttribute("data-value"));
      applyPrefs(); renderSettings();
    }
    else if (action === "retry-voice") paintView(voiceFormHtml(target.getAttribute("data-kind")));
  });
  document.addEventListener("submit", function (event) {
    var searchForm = event.target.closest ? event.target.closest("form[data-search]") : null;
    if (searchForm) {
      event.preventDefault();
      var input = searchForm.querySelector('input[name="q"]');
      var query = input ? input.value.trim() : "";
      if (query) location.hash = "#/search/" + encodeURIComponent(query);
      return;
    }
    var voiceForm = event.target.closest ? event.target.closest("form[data-voice-form]") : null;
    if (voiceForm) {
      event.preventDefault();
      handleVoiceSubmit(voiceForm);
    }
  });
  document.addEventListener("keydown", function (event) {
    if (event.key === "Escape") closeSettings();
  });

  /* ---------------- analytics (optional, config.js: analyticsId) ----------------
     NOVA is a single hash-routed page, so GA's own automatic pageview only
     fires once on load. We turn that off (send_page_view: false) and fire
     a page_view event ourselves on every route change instead, so each
     note/subject/etc. visited actually counts as its own pageview. */
  function initAnalytics() {
    var id = CFG.analyticsId && String(CFG.analyticsId).trim();
    if (!id) return;
    window.dataLayer = window.dataLayer || [];
    function gtag() { window.dataLayer.push(arguments); }
    window.gtag = gtag;
    gtag("js", new Date());
    gtag("config", id, { send_page_view: false });
    var script = document.createElement("script");
    script.async = true;
    script.src = "https://www.googletagmanager.com/gtag/js?id=" + encodeURIComponent(id);
    document.head.appendChild(script);
  }
  function trackPageview(current) {
    if (!window.gtag) return;
    var path = "/" + (current.name || "home") + (current.parts.length ? "/" + current.parts.join("/") : "");
    window.gtag("event", "page_view", {
      page_path: "#" + path,
      page_title: document.title,
      page_location: location.href
    });
  }

  /* ---------------- boot ---------------- */
  function init() {
    appEl = document.getElementById("app");
    layerEl = document.getElementById("settings-layer");
    if (!appEl || !layerEl) {
      console.error("[cairn] required containers missing");
      return;
    }
    applyPrefs();
    initAnalytics();
    window.addEventListener("hashchange", function () {
      closeSettings();
      render();
    });
    loadManifest().then(render);
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
